github.com:
    users:
        shreyasiddheshwar12:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: shreyasiddheshwar12
